### ISSUE TITLE
nw-wrap errors

### ISSUE THREAD

**Issue by MartySVK** [spelufo/nw-wrap#1]
Hi,
I am trying to use your nw-wrap, but everytime I will get these errors.

Can you check?

```
$ node_modules/.bin/nw-wrap
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-webkit ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:139:18)
    at node.js:999:3

```

**Comment by spelufo** [comment]
Do you have node-webkit installed? It is now called nwjs, and I don't know if it still has the same issues with stdio. What is likely happening is that your nwjs executable is not called `node-webkit`, as this module expects. You can run `NW_CMD=path/to/nw node_modules/.bin/nw-wrap` to use another executable.

If this module is still useful, and people are still running into the same stdio issues in nwjs as there were in node-webkit, I should probably make `nw` the default, but I don't know, since I haven't used node-webkit/nwjs in a while.

**Comment by derrickb** [comment]
Hi @spelufo, just started with nwjs for the first, have the latest version 0.25.3.

First of all, the stdin issue appears to still be there, which is why I tried nw-wrap.  I needed to change the path to the executable as you wrote in your comment.

If possible, it would be much appreciated if you could update nw-wrap to use `nw` by default.
